version: 2.1

executors:
  pulumi:
    docker:
      - image: circleci/node:14

jobs:
  make:
    executor: pulumi
    steps:
      - checkout
      - run:
          command: "printf '//registry.npmjs.org/:_authToken=%s' \"${NPM_TOKEN}\" > .npmrc"
      - run:
          command: "npm ci"
      - run:
          command: "npm run build"
      - run:
          command: "npm run test"
      - run:
          command: "npm run coverage"
      - run:
          command: "npm run codeclimate"
      - run:
          command: "npm publish"

workflows:
  version: 2
  build-main:
    jobs:
      - make:
          name: make
