version: 2.1

executors:
  pulumi:
    docker:
      - image: circleci/node:14

jobs:
  make:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: "make install"
      - run:
          command: "make test"

workflows:
  version: 2
  build-master:
    jobs:
      - make:
        name: make
